### ISSUE TITLE
Update Outdated NATS/Jetstream Documentation

### ISSUE THREAD

**Issue by JeanPierreNell** [tazama-lf/General-Issues#221]
Update outdated Jetstream and NATS Documentation

- [ ] Startup Library Documentation
- [ ] TMS 
- [ ] Typology Processor
- [ ] Rule Executor
- [ ] TADP
- [ ] Case Management System

**Comment by Justus-at-Tazama** [comment]
Action: reconcile existing documentation to check if this issue is still an issue.

**Comment by Sandy-at-Tazama** [comment]
Additional documentation provided
